-- ==============================
-- CREAR USUARIO DE LA APLICACIÓN
-- ==============================

CREATE USER GESTION_EDUCATIVA IDENTIFIED BY gestion123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;
-- ==============================
-- ASIGNAR PRIVILEGIOS
-- ==============================

GRANT CONNECT, RESOURCE TO GESTION_EDUCATIVA;
GRANT CREATE TABLE TO GESTION_EDUCATIVA;
GRANT CREATE SEQUENCE TO GESTION_EDUCATIVA;
GRANT CREATE VIEW TO GESTION_EDUCATIVA;